### ISSUE TITLE
import不了

### ISSUE THREAD

**Issue by qinidea** [andywj/cloudbase_flutter_nullsafety_sdk#1]
cloudbase_auth_nullsafety.dart缺少了library语句？

**Comment by andywj** [comment]
import 'package:cloudbase_auth_nullsafety/cloudbase_auth_nullsafety.dart';

**Comment by andywj** [comment]
目前自用使用都没有遇到导入的问题 需要确认下版本是不是0.0.2

**Comment by qinidea** [comment]
谢谢。时间有点久，忘了具体现象了。现在是正常的。
